
name: LaTeX Build

on:
  push:
    branches: [ main, dev-ci-test ]
    
#   workflow_dispatch:

jobs:

  latex-assemble:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v3

      - name: Markdown Generation
        run: |
          .github/workflows/python merge_markdowns.py

#       - name: Run a multi-line script
#         run: |
#           echo Add other actions to build,
#           echo test, and deploy your project.
          
#       - name: LaTeX compilation
#         uses: dante-ev/latex-action@2021-A

